spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dinner?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  mail:
    username: 18715851323@163.com
    password: GJTKCGKZNQDZSQFW
    protocol: smtp
    default-encoding: utf-8
    host: smtp.163.com
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"